# Generated by Django 5.1.2 on 2025-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('impact_v2', models.JSONField(blank=True, null=True)),
                ('impact_v3', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
