# Generated by Django 5.1.2 on 2025-02-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve',
            name='last_modified_date',
        ),
    ]
