# Generated by Django 5.1.2 on 2025-02-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_cve_last_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPEC',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Generic Name', max_length=255)),
                ('abstraction', models.CharField(choices=[('Meta', 'Meta'), ('Standard', 'Standard'), ('Detailed', 'Detailed')], default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('Stable', 'Stable'), ('Deprecated', 'Deprecated'), ('Draft', 'Draft'), ('Incomplete', 'Incomplete'), ('Obsolete', 'Obsolete'), ('Usable', 'Usable')], default='Draft', max_length=50)),
                ('likelihood_of_attack', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('typical_severity', models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_aggregated', models.TextField(blank=True, null=True)),
                ('extended_description', models.TextField(blank=True, null=True)),
                ('extended_description_aggregated', models.TextField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('indicators_aggregated', models.TextField(blank=True, null=True)),
                ('prerequisites', models.JSONField(blank=True, null=True)),
                ('prerequisites_aggregated', models.TextField(blank=True, null=True)),
                ('resources_required', models.JSONField(blank=True, null=True)),
                ('resources_required_aggregated', models.TextField(blank=True, null=True)),
                ('mitigations', models.JSONField(blank=True, null=True)),
                ('mitigations_aggregated', models.TextField(blank=True, null=True)),
                ('example_instances', models.JSONField(blank=True, null=True)),
                ('example_instances_aggregated', models.TextField(blank=True, null=True)),
                ('consequences', models.JSONField(blank=True, null=True)),
                ('consequences_aggregated', models.TextField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, null=True)),
                ('skills_required_aggregated', models.TextField(blank=True, null=True)),
                ('alternate_terms', models.JSONField(blank=True, null=True)),
                ('alternate_terms_aggregated', models.TextField(blank=True, null=True)),
                ('overall_aggregated_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CAPECRelatedAttackPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('ChildOf', 'ChildOf'), ('ParentOf', 'ParentOf'), ('PeerOf', 'PeerOf'), ('CanAlsoBe', 'CanAlsoBe'), ('CanFollow', 'CanFollow'), ('CanPrecede', 'CanPrecede')], max_length=20)),
                ('source_capec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_related_patterns', to='data.capec')),
                ('target_capec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_related_patterns', to='data.capec')),
            ],
            options={
                'unique_together': {('source_capec', 'target_capec', 'nature')},
            },
        ),
        migrations.AddField(
            model_name='capec',
            name='related_patterns',
            field=models.ManyToManyField(blank=True, through='data.CAPECRelatedAttackPattern', to='data.capec'),
        ),
        migrations.CreateModel(
            name='ExecutionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_flow', to='data.capec')),
            ],
        ),
        migrations.AddField(
            model_name='capec',
            name='execution_flow_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_capec', to='data.executionflow'),
        ),
        migrations.CreateModel(
            name='AttackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_aggregated', models.TextField(blank=True, null=True)),
                ('techniques', models.JSONField(blank=True, null=True)),
                ('techniques_aggregated', models.TextField(blank=True, null=True)),
                ('execution_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_steps', to='data.executionflow')),
            ],
        ),
    ]
