# Usa un'immagine base con supporto CUDA
FROM nvidia/cuda:12.2.2-devel-ubuntu22.04 AS cuda_installer

# Installa Python e pip
RUN apt-get update && apt-get install -y python3 python3-pip curl && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    python -m pip install --upgrade pip

# Copia lo script per installare CUDA
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN /entrypoint.sh