# Generated by Django 5.1.2 on 2025-02-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('correlation', 'Correlation')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=50)),
                ('cve_hosts', models.JSONField(null=True)),
                ('ai_models', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('cve_id', models.CharField(max_length=20)),
                ('similarity_scores', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_correlations', to='core.task')),
            ],
        ),
    ]
