# Generated by Django 5.1.2 on 2025-02-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('correlation', 'Correlation')], default='correlation', max_length=50),
        ),
    ]
