# Generated by Django 5.1.2 on 2025-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
